name: Feature / Open PR to Develop

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Feature / Open PR to Develop
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
    steps:

      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Build application
        working-directory: ./src
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        working-directory: ./src
        run: dotnet test --no-restore --verbosity normal
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
  pull-request:
    name: Open PR to develop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "develop"
        pr_title: "Pulling ${{ github.ref }} into develop"
        pr_body: "[FTR] Automated PR from feature to develop"
        pr_reviewer: "enzotlucas"
        pr_assignee: "enzotlucas"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
